"""
AutoKernel -- E2FGVIHD experiment entrypoint.

The benchmark harness calls kernel_fn(frames, masks) and compares the returned
NumPy array to the baseline_output.npy generated by prepare.py.
"""

from __future__ import annotations

import numpy as np

from sorawm.cleaner.e2fgvi_hq_cleaner import E2FGVIHDCleaner, E2FGVIHDConfig

KERNEL_TYPE = "e2fgvihd_clean"

_cleaner: E2FGVIHDCleaner | None = None


def _get_cleaner() -> E2FGVIHDCleaner:
    global _cleaner
    if _cleaner is None:
        config = E2FGVIHDConfig(enable_torch_compile=False, use_bf16=False)
        _cleaner = E2FGVIHDCleaner(load_weights=True, config=config)
    return _cleaner


def _stack_outputs(out_frames: list[np.ndarray] | np.ndarray) -> np.ndarray:
    if isinstance(out_frames, np.ndarray):
        return out_frames.astype(np.float32, copy=False)
    return np.stack([np.asarray(frame) for frame in out_frames], axis=0).astype(np.float32)


def kernel_fn(frames: np.ndarray, masks: np.ndarray) -> np.ndarray:
    return _stack_outputs(_get_cleaner().clean(frames, masks))
